# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/kubernetes-sigs/yaml
%global goipath         sigs.k8s.io/yaml
%global goaltipaths     sigs.k8s.io/yaml/goyaml.v2 sigs.k8s.io/yaml/goyaml.v3
%global forgeurl        https://github.com/kubernetes-sigs/yaml
Version:                1.4.0

%gometa -f


%global common_description %{expand:
A better way to marshal and unmarshal YAML in Golang.}

%global golicenses      LICENSE goyaml.v2/LICENSE goyaml.v2/LICENSE.libyaml\\\
                        goyaml.v2/NOTICE goyaml.v3/LICENSE goyaml.v3/NOTICE
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A better way to marshal and unmarshal YAML in Golang

License:        Apache-2.0 AND MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
