# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/kubernetes-sigs/controller-runtime
%global goipath         sigs.k8s.io/controller-runtime
%global forgeurl        https://github.com/kubernetes-sigs/controller-runtime
Version:                0.16.4

%gometa -f


%global common_description %{expand:
Repo for the controller-runtime subproject of kubebuilder (sig-apimachinery).}

%global golicenses      LICENSE
%global godocs          examples CONTRIBUTING.md FAQ.md README.md TMP-\\\
                        LOGGING.md VERSIONING.md code-of-conduct.md\\\
                        RELEASE.md designs/README.md designs/cache_options.md\\\
                        designs/component-config.md designs/move-cluster-\\\
                        specific-code-out-of-manager.md designs/template.md\\\
                        designs/use-selectors-at-cache.md tools/setup-\\\
                        envtest/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Repo for the controller-runtime subproject of kubebuilder (sig-apimachinery)

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc examples CONTRIBUTING.md FAQ.md README.md TMP-LOGGING.md VERSIONING.md
%doc code-of-conduct.md RELEASE.md designs/README.md designs/cache_options.md
%doc designs/component-config.md
%doc designs/move-cluster-specific-code-out-of-manager.md designs/template.md
%doc designs/use-selectors-at-cache.md tools/setup-envtest/README.md

%gopkgfiles

%changelog
%autochangelog
