# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/gomodules/jsonpatch
%global goipath         gomodules.xyz/jsonpatch/v2
%global forgeurl        https://github.com/gomodules/jsonpatch
Version:                2.4.0
%global tag             v2.4.0

%gometa -f


%global common_description %{expand:
Generate JSON Patch as specified in RFC 6902 from the IETF.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Generate JSON Patch as specified in RFC 6902 from the IETF

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1
mv v2/* .

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
