# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/google/gnostic-models
%global goipath         github.com/google/gnostic-models
Version:                0.6.8

%gometa -f


%global common_description %{expand:
Protocol Buffer models and associated libraries for 
working with API description formats supported by gnostic}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md compiler/README.md\\\
                        discovery/README.md extensions/README.md\\\
                        jsonschema/README.md openapiv2/README.md\\\
                        openapiv3/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Protocol Buffer models for API description formats supported by gnostic

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CONTRIBUTING.md README.md compiler/README.md discovery/README.md
%doc extensions/README.md jsonschema/README.md openapiv2/README.md
%doc openapiv3/README.md

%gopkgfiles

%changelog
%autochangelog
